CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(32) NOT NULL,
passwd VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS tweets(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER REFERENCES users(id) NOT NULL,
tw_time TEXT NOT NULL,
body VARCHAR(140) NULL
);
